# Generated by Django 4.1.2 on 2022-10-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
