# Generated by Django 4.1.2 on 2022-10-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_create_date_questions_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
